const SET_MAP_COORDS_FLAG = 'GET_MAP_COORDS_FLAG'
const CLEAN_MAP_COORDS_FLAG = 'CLEAN_MAP_COORDS_FLAG'
const SET_REGISTER_COORDS_FLAG = 'SET_REGISTER_COORDS_FLAG'
const CLEAN_REGISTER_COORDS_FLAG = 'CLEAN_REGISTER_COORDS_FLAG'
const STORE_MAP_COORDS = 'STORE_MAP_COORDS'
const SET_SUBMIT_MESSAGE = 'SET_SUBMIT_MESSAGE'
const CLEAN_SUBMIT_MESSAGE = 'CLEAN_SUBMIT_MESSAGE'

export {
    SET_MAP_COORDS_FLAG,
    CLEAN_MAP_COORDS_FLAG,
    SET_REGISTER_COORDS_FLAG,
    CLEAN_REGISTER_COORDS_FLAG,
    STORE_MAP_COORDS,
    SET_SUBMIT_MESSAGE,
    CLEAN_SUBMIT_MESSAGE
}