const SET_MAP_COORDS_FLAG = 'GET_MAP_COORDS_FLAG'
const CLEAN_MAP_COORDS_FLAG = 'CLEAN_MAP_COORDS_FLAG'
const SET_REGISTER_COORDS_FLAG = 'SET_REGISTER_COORDS_FLAG'
const CLEAN_REGISTER_COORDS_FLAG = 'CLEAN_REGISTER_COORDS_FLAG'
const STORE_MAP_COORDS = 'STORE_MAP_COORDS'

export {
    SET_MAP_COORDS_FLAG,
    CLEAN_MAP_COORDS_FLAG,
    SET_REGISTER_COORDS_FLAG,
    CLEAN_REGISTER_COORDS_FLAG,
    STORE_MAP_COORDS
}